-- MySQL Script generated by MySQL Workbench
-- Fri May 20 23:23:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ucaldas_prog3_aph
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ucaldas_prog3_aph` ;

-- -----------------------------------------------------
-- Schema ucaldas_prog3_aph
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ucaldas_prog3_aph` DEFAULT CHARACTER SET utf8 ;
USE `ucaldas_prog3_aph` ;

-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmseccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmseccion` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmseccion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmtipoinmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmtipoinmueble` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmtipoinmueble` (
  `idTipoInmueble` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `descripcion` VARCHAR(400) NULL DEFAULT NULL,
  PRIMARY KEY (`idTipoInmueble`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tususuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tususuario` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tususuario` (
  `nroDocumento` INT NOT NULL,
  `primerNombre` VARCHAR(80) NOT NULL,
  `segundoNombre` VARCHAR(80) NULL DEFAULT NULL,
  `primerApellido` VARCHAR(200) NOT NULL,
  `segundoApellido` VARCHAR(200) NULL DEFAULT NULL,
  `email` VARCHAR(100) NOT NULL,
  `celular` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`nroDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadminmueble`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadminmueble` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadminmueble` (
  `idInmueble` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(45) NULL DEFAULT NULL,
  `nroDocumentoPropietario` INT NOT NULL,
  `nroDocumentoHabitante` INT NOT NULL,
  `idTipoInmueble` INT NOT NULL,
  `idSeccion` INT NOT NULL,
  PRIMARY KEY (`idInmueble`),
  INDEX `fk_tadm_inmueble_nroDocumentoPropietario_idx` (`nroDocumentoPropietario` ASC) VISIBLE,
  INDEX `fk_tadm_inmueble_nroDocumentoHabitante_idx` (`nroDocumentoHabitante` ASC) VISIBLE,
  INDEX `fk_tadm_inmueble_idTipoInmueble_idx` (`idTipoInmueble` ASC) VISIBLE,
  INDEX `fk_tadm_inmueble_idSeccion_idx` (`idSeccion` ASC) VISIBLE,
  CONSTRAINT `fk_tadm_inmueble_idSeccion`
    FOREIGN KEY (`idSeccion`)
    REFERENCES `ucaldas_prog3_aph`.`tadmseccion` (`id`),
  CONSTRAINT `fk_tadm_inmueble_idTipoInmueble`
    FOREIGN KEY (`idTipoInmueble`)
    REFERENCES `ucaldas_prog3_aph`.`tadmtipoinmueble` (`idTipoInmueble`),
  CONSTRAINT `fk_tadm_inmueble_nroDocumentoHabitante`
    FOREIGN KEY (`nroDocumentoHabitante`)
    REFERENCES `ucaldas_prog3_aph`.`tususuario` (`nroDocumento`),
  CONSTRAINT `fk_tadm_inmueble_nroDocumentoPropietario`
    FOREIGN KEY (`nroDocumentoPropietario`)
    REFERENCES `ucaldas_prog3_aph`.`tususuario` (`nroDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadminmueblesadicionales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadminmueblesadicionales` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadminmueblesadicionales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `area` VARCHAR(200) NULL DEFAULT NULL,
  `tipoInmuebleAdicional` VARCHAR(50) NOT NULL,
  `idInmueble` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tadm_inmueblesAdicionales_idInmueble_idx` (`idInmueble` ASC) VISIBLE,
  CONSTRAINT `fk_tadm_inmueblesAdicionales_idInmueble`
    FOREIGN KEY (`idInmueble`)
    REFERENCES `ucaldas_prog3_aph`.`tadminmueble` (`idInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmmulta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmmulta` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmmulta` (
  `idMulta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `valor` INT NOT NULL,
  `descripcion` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`idMulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmmultausuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmmultausuario` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmmultausuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idMulta` INT NOT NULL,
  `nroDocumento` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tadm_multaUsuario_nroIdentificacion_idx` (`nroDocumento` ASC) VISIBLE,
  INDEX `fk_tadm_multaUsuario_idMulta` (`idMulta` ASC) VISIBLE,
  CONSTRAINT `fk_tadm_multaUsuario_idMulta`
    FOREIGN KEY (`idMulta`)
    REFERENCES `ucaldas_prog3_aph`.`tadmmulta` (`idMulta`),
  CONSTRAINT `fk_tadm_multaUsuario_nroIdentificacion`
    FOREIGN KEY (`nroDocumento`)
    REFERENCES `ucaldas_prog3_aph`.`tususuario` (`nroDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmzonasocial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmzonasocial` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmzonasocial` (
  `idZonaSocial` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `rutaFotografia` VARCHAR(200) NULL DEFAULT NULL,
  `descripcion` VARCHAR(450) NULL DEFAULT NULL,
  `costoAlquiler` INT NOT NULL,
  `horarioAcceso` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idZonaSocial`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '					';


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tadmzonasocialusuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tadmzonasocialusuario` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tadmzonasocialusuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idZonaSocial` INT NOT NULL,
  `nroDocumento` INT NOT NULL,
  `fechaUso` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `fechaUso_UNIQUE` (`fechaUso` ASC) VISIBLE,
  INDEX `fk_tadm_zonaSocialUsuario_nroDocumento_idx` (`nroDocumento` ASC) VISIBLE,
  INDEX `fk_tadm_zonaSocialUsuario_idZonaSocial` (`idZonaSocial` ASC) VISIBLE,
  CONSTRAINT `fk_tadm_zonaSocialUsuario_idZonaSocial`
    FOREIGN KEY (`idZonaSocial`)
    REFERENCES `ucaldas_prog3_aph`.`tadmzonasocial` (`idZonaSocial`),
  CONSTRAINT `fk_tadm_zonaSocialUsuario_nroDocumento`
    FOREIGN KEY (`nroDocumento`)
    REFERENCES `ucaldas_prog3_aph`.`tususuario` (`nroDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tfaccreditoinmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tfaccreditoinmuebles` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tfaccreditoinmuebles` (
  `idCreditoInmueble` INT NOT NULL,
  `idInmueble` INT NOT NULL,
  `valor` INT NOT NULL,
  `motivo` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idCreditoInmueble`, `idInmueble`),
  INDEX `fk_tfac_creditoInmuebles_idInmueble_idx` (`idInmueble` ASC) VISIBLE,
  CONSTRAINT `fk_tfac_creditoInmuebles_idInmueble`
    FOREIGN KEY (`idInmueble`)
    REFERENCES `ucaldas_prog3_aph`.`tadminmueble` (`idInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'El saldo podrá ser credito (valores positivos)';


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tfacdebitoinmuebles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tfacdebitoinmuebles` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tfacdebitoinmuebles` (
  `idDebitoInmueble` INT NOT NULL,
  `idInmueble` INT NOT NULL,
  `valor` INT NOT NULL,
  `motivo` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`idDebitoInmueble`, `idInmueble`),
  INDEX `fk_tfac_debitoInmuebles_idInmueble_idx` (`idInmueble` ASC) VISIBLE,
  CONSTRAINT `fk_tfac_debitoInmuebles_idInmueble`
    FOREIGN KEY (`idInmueble`)
    REFERENCES `ucaldas_prog3_aph`.`tadminmueble` (`idInmueble`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = 'El saldo podrá ser debito (valores negativos)';


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tgeparametros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tgeparametros` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tgeparametros` (
  `idParametro` INT NOT NULL AUTO_INCREMENT,
  `etiqueta` VARCHAR(200) NOT NULL,
  `valor` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`idParametro`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tusrol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tusrol` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tusrol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(450) NULL DEFAULT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `ucaldas_prog3_aph`.`tususuariorol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ucaldas_prog3_aph`.`tususuariorol` ;

CREATE TABLE IF NOT EXISTS `ucaldas_prog3_aph`.`tususuariorol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nroDocumento` INT NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarioRol_idRol_idx` (`idRol` ASC) VISIBLE,
  INDEX `fk_usuarioRol_nroDocumento` (`nroDocumento` ASC) VISIBLE,
  CONSTRAINT `fk_usuarioRol_idRol`
    FOREIGN KEY (`idRol`)
    REFERENCES `ucaldas_prog3_aph`.`tusrol` (`idRol`),
  CONSTRAINT `fk_usuarioRol_nroDocumento`
    FOREIGN KEY (`nroDocumento`)
    REFERENCES `ucaldas_prog3_aph`.`tususuario` (`nroDocumento`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
